title: A collection of useful link on ML
logo: /assets/img/logo.png
description: csabaiBio group - study material on machine learning
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
